### ISSUE TITLE
Comments

### ISSUE THREAD

**Issue by junction10** [willthames/photodeck.lrdevplugin#1]
Hi Will,

Just a quick question - will the plugin sync existing galleries - ie:  Search Photodeck for images that exist in the current Lightroom library (and pair up with original RAW files if necessary?).
Photoshelter plugin by PACT Software adds metadata to the Lightroom library that stores the unique image identifier (which also forms part of the URL) in the image that is published - so that avoids any confusion if two files exist in the Lightroom library with the same filename...  

Also - If you use the plugin after your Photodeck account is already up and running, will the photodeck plugin eventually allow selection of galleries and subgalleries?  It appears currently it only allows the creation of galleries at the top level...  I keep my galleries in various sub-galleries.

What happens if you create a gallery in the plugin, then move the gallery on the website..  will the plugin keep track?

Kind regards,

Jason Sheldon
jason@junction10.net

**Comment by willthames** [comment]
Hi Jason,
There is no real way that the plugin can work out that a file on PhotoDeck corresponds to a file in Lightroom before the plugin has published it. As each image is published, the plugin stores the photodeck ID with the image, but this cannot be done retrospectively. I'm not aware of a mechanism for achieving this I'm afraid.

The plugin copes with sub-galleries just fine - parent galleries are just called folders. So create folders and then galleries under the folders. You can have more than one layer of folders too should you need sub-sub-galleries.

The plugin copes with existing galleries and folders if you recreate the structure under the plugin. You could move the gallery in Photodeck after creation and it should just work (the plugin stores the photodeck ID for the gallery) but I would probably recommend renaming or reparenting the galleries from within Lightroom. 

In general my advice would be that if you are going to use the plugin, do as much as you can through the plugin (so publish all your images and maintain gallery structure etc) and do what remains (pricing policies, folder cover image, sort order etc.) through Photodeck. Updating stuff in Photodeck that the plugin attempts to take care of may cause problems (mostly unnecessary extra republishes rather than anything more serious).

Thanks for your questions, I hope I've answered them clearly - if not, just let me know and I'll try and explain better!

**Comment by cmaion** [comment]
Closing this: two-way gallery structure synchronization and sub-galleries support are implemented.
Synchronization of gallery content remains TBD.
