### ISSUE TITLE
How to 'update' without losing publishing history?

### ISSUE THREAD

**Issue by junction10** [willthames/photodeck.lrdevplugin#8]
When I updated to v12, it created a new instance of Photodeck publishing collection in my cataloge, so I went through and manually updated the collection, which meant I had to delete the images from my Photodeck galleries, and reupload them from Lightroom (otherwise I ended up with duplicates on Photodeck, but with only the newly uploaded files showing in my Photodeck collection in Lightroom).

Anyway - I've just downloaded v14 and the zip files contain the .LUA files, which I copied into the existing package in the Lightroom Modules folder..  overwriting the existing LUA files..

When I relaunch Lightroom, it says the plugin is missing..  but if I go to configure it, it creates a new Photodeck collection - and I don't want to have to reupload all my photos again after starting with an empty collection...

How do we update the plugin safely without losing our changes in Lightroom?

**Comment by cmaion** [comment]
Hi,

Are you on Windows or MacOS ?
This should not be happening.

Simply overwriting existing files should be enough. Lightroom should get the new plugin version upon reload or restart without having to touch the catalogue.
Make sure that the zip archive is properly uncompressed? (at the exact location where Lightroom expects it)

If you are still stuck, send a screenshot of both Lightroom and your file manager to PhotoDeck support!

**Comment by junction10** [comment]
Hi,

I’m on Mac OSX.  I’ve resolved it - I’d downloaded the zip file from the GITHUB repository which is .lrDEVplugin - but on the Photodeck download page, 14 is available as .lrplugin (I guess compiled?)..  

I would have thought simply replacing the LUA’s wouldn’t have made any difference, but obviously it does..  anyway, I’ve got it working again now by using the version from the Photodeck site rather than github.

By the way - I’d like to show my appreciation for the development of the plugin.  Is there any page to make a donation in lieu of registration? 

Kind regards,

Jason Sheldon
Junction10.Photography <http://www.junction10.photography/>
mobile: 07973 618503
twitter:  @junction10 <http://www.twitter.com/junction10>
Terms and conditions of business here <http://www.junction10.photography/terms>

**Comment by cmaion** [comment]
Glad you got it solved, good to know.
The issue was probably due to the fact that the GitHub plugin doesn't carry the same internal name (used in the Lightroom catalogue) than the official (and compiled ;) ) one.

And thank you for your kind offer! you should ask Will, he is the one who started all of this ;)

Thanks,
Cedric

**Comment by willthames** [comment]
Yes, was going to suggest that this is usually caused by a change to the LrToolkitIdentifier. For backward compatibility reasons, my version has to retain its name (otherwise my primary user would have to have to redo her catalogue as you experience).

In terms of donation, I'd rather it went to a worthy cause. Find someone doing something awesome for a good charity, and stick an amount of your choosing in their (possibly online) collection tin. (That's my favourite way of donating to charity, as a runner/former triathlete)
